### ISSUE TITLE
Field specs missing in request/response model

### ISSUE THREAD

**Issue by robbito** [mrin9/RapiPdf#13]
I have specified @Size annotations, which are not rendered in the model:
![image](https://user-images.githubusercontent.com/7056064/64607686-49b50c80-d3c9-11e9-9591-662f15a03975.png)
![image](https://user-images.githubusercontent.com/7056064/64607726-618c9080-d3c9-11e9-8fda-045c662a6e36.png)

**Comment by robbito** [comment]
Here is a minimal api spec:

[openapi.zip](https://github.com/mrin9/RapiPdf/files/3610010/openapi.zip)

**Comment by mrin9** [comment]
Currently we show `type, format, patterns and constrain` info for `query, form, path and header` params.
For `request-body`  which generally is an object we are having some internal discussion on how best we can put this info in a printable manner without skewing the objects indentation structure. We have some designs that we are running through our test cases and collecting feedbacks from some of our clients.

we do have a plan to show this info and as you correctly mentioned we already have done some ground work for it `getTypeInfo()`. 

> Regarding the code, one of our top priority is apply a [JS style linter ](https://stylelint.io/). If you are willing, I am happy to take a PR on this. the first step would be to just lint it without changing any names, thereafter we visit the rest

**Comment by mrin9** [comment]
in release `2.0.0` code has been refactored and  JS linter is applied. Type info about field types are now printed in the  object model.
