### ISSUE TITLE
readOnly parameters are included in requests

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiPdf#28]
I mark any service-generated parameters as readOnly, such as UUIDs and timestamps for when resources are created and updated. The parameters should only be shown in responses, never in requests. RapiPdf includes those parameters in requests, which is confusing. It does show "read-only" in the type column, but that's not as clear as not showing those parameters at all for requests.
That is, it's better to say that a request body includes A, B, and C instead of A, B, C, and D, but D is read-only.

**Comment by mrin9** [comment]
In our roadmap we have plans to print the examples for request and responses, when we do that we will be omitting the readonly params in generated examples, but we do have an opinion to display all fields and their constraints when it comes to printing the schema.
something we did it in our online renderer [RapiDoc](https://mrin9.github.io/RapiDoc/tests/data-types.html) this is also the case with SwaggerUI
