### ISSUE TITLE
PDF generation not working on example page

### ISSUE THREAD

**Issue by transitive-bullshit** [mrin9/RapiPdf#31]
I'm interested in using this lib, but the examples on the linked website open a new tab with nothing happening or downloading.

(using mac os catalina and latest chrome stable)

**Comment by mrin9** [comment]
you should remove any ad-blocker if they exist

**Comment by Hipska** [comment]
Also, it seems that the examples don't parse markdown links in the description.

**Comment by mrin9** [comment]
we try to cover most of the markdown syntax, but there are still gaps, like images are not supported.

Can you point me to the place where you see that markdowns are not supported ?
