### ISSUE TITLE
Always display full width tables

### ISSUE THREAD

**Issue by GitGraf** [mrin9/RapiPdf#32]
When generating my PDF, I noticed that some tables are smaller than others, because they feature less content. Is it possible to configure RapiPdf to always make them full width?
![rapipdf_tables](https://user-images.githubusercontent.com/19150483/73055532-4d839000-3e8d-11ea-96dc-7f09df81524d.PNG)

**Comment by mrin9** [comment]
It is possible, and at some point in time we were doing that, then we received some user feedback that
- it creates a lot of noise in the prints, 
- makes the document appear tired looking and long even though it has less text overall,
- not visually appealing in case of tables with smaller content, as the content is always tucked on left side whereas the reduced width looks cleaner
- waste ink.
 most of these feedback are from medium to large documents, spanning more than 300 - 700 pages

but if you have some reasons or strong opinion to make them span full width, please list them, and I will run it through our usability team
