### ISSUE TITLE
Last page always empty

### ISSUE THREAD

**Issue by LevinGuy** [mrin9/RapiPdf#39]
Hi,

It seems that the last page of every generated PDF is empty.

Thanks,
Guy

**Comment by stevenj** [comment]
I think that's an artefact of the "include-api-list" option.  If you set that option to true, the last page isn't empty any more.

**Comment by yj-ang** [comment]
I have encountered the same issue.

Trying to fix it with [#56 ](https://github.com/mrin9/RapiPdf/pull/56)
