### ISSUE TITLE
Markdown and HTML tables do not show up in output PDF

### ISSUE THREAD

**Issue by spurle01** [mrin9/RapiPdf#49]
Tried converting an OpenAPI Spec with a description that includes both a GitHub Format Markup table and an HTML table and both were excluded from the PDF that was produced.  Both tables are displayed correctly via Swagger Editor/UI.

Example spec exhibiting the behavior described above:
[openapi.txt](https://github.com/mrin9/RapiPdf/files/4478652/openapi.txt)

**Comment by mrin9** [comment]
Markdown support is not supported that well in RapiPDF. I will try to improve this a little bit more.

Closing this issues in favor of #53
