### ISSUE TITLE
At the moment it's not working, 1.0.3

### ISSUE THREAD

**Issue by coder82** [mrin9/RapiPdf#5]
When clicking the generate pdf button in chrome it opens a blank page and it closes it immediately.
I don't see the pdf. If I disable the chrome pdf display from the settings, then I get to download the pdf correctly. Any idea how to fix this? The demo from website doesn't work either, same issue.
So in browser pdf preview is not working.

This is the setting I have to change in chrome:
https://i.imgur.com/cLaDzFy.png

**Comment by mrin9** [comment]
currently we too are struggling with this issue, we do not have any solution yet :(

**Comment by mrin9** [comment]
after updating some dependencies (release 1.0.5),  we got it working for our [demo](https://mrin9.github.io/RapiPdf/).

Can you confirm if it resolves your case ?

**Comment by ng1905** [comment]
This issue still exists for me. Even the demo shows the exact same behaviour. 

Chrome version 77.0.3865.90

**Comment by coder82** [comment]
Still doesn't work, same version as above.

**Comment by milesje** [comment]
@mrin9 This is still not working, has there been any movement/work on this issue. I noticed that you closed the issue... but it is still not working.

**Comment by coder82** [comment]
This is still not working in version 2.1.0
Chrome 78.0.3904.108 
It opens a tab and then it closed it, no message, nothing shown, nothing happens.
@mrin9 is it still working for you?

**Comment by mrin9** [comment]
Please ensure that you are not running any ad-blocker or popup blocker
