### ISSUE TITLE
RapiPdf Doesn't support unicode.

### ISSUE THREAD

**Issue by ichaozai** [mrin9/RapiPdf#50]
Unicode characters (such as Chinese or Japanese) are blank in the generated pdf.

**Comment by mrin9** [comment]
can you provide me with an example spec ?

**Comment by ichaozai** [comment]
This is a simple spec contains Chinese characters.
```json
openapi: 3.0.1
info:
  title: 接口
  description: REST API 接口
  version: 1.0.0
paths:
  /api/api:
    post:
      summary: 传入图片
      operationId: handle_image
      requestBody:
        description: 图像二进制文件
        content:
          image/jpeg:
            schema:
              type: string
              format: binary
        required: true
      responses:
        200:
          description: 图像
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
```

This is the generated pdf.
[1b56bdfd-6737-4832-ba51-655bfea8f56b.pdf](https://github.com/mrin9/RapiPdf/files/4527208/1b56bdfd-6737-4832-ba51-655bfea8f56b.pdf)

**Comment by mrin9** [comment]
do you know an open-source font that can support these characters ? 
I am using Roboto, but looks like it do not support Chinese

**Comment by ichaozai** [comment]
There are [some fonts](https://fonts.google.com/?subset=chinese-simplified) support Chinese.  
But It's not easy to find font support all other languages (such as Japanese, Korean).

To solve the languages support missing problem, is there any ways to congifure fonts easily?

**Comment by mrin9** [comment]
I am afraid, there isnt an easy way for now, you need to build the source by yourself after replacing the font

we use PDFMake library to generate the PDF
you may checkout https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/ on how to add your own font
