### ISSUE TITLE
Duplicate Table Header at end of a page and start of next page.

### ISSUE THREAD

**Issue by rknuc12345** [mrin9/RapiPdf#51]

**Comment by mrin9** [comment]
Any table that spans across the page, then the headers are repeated. 
It is by design. If we don repeat the header, then in this case the header would have appeared at the bottom of the page and the body would have come in the next page, which IMO is more troublesome

**Comment by rknuc12345** [comment]
I got you. Thanks for your explainantion @mrin9.
