### ISSUE TITLE
Nested lists in description not supported

### ISSUE THREAD

**Issue by andyrooger** [mrin9/RapiPdf#53]
Nested lists don't seem to be supported when writing MD in the spec description.

**Repro**

info.description:
```md
- item 1
- item 2
  - item 2.1
  - item 2.2
- item 2
```

Result:
```
* item 1
* item 2
* item 2.1
* item 2.2
```

This becomes a flat list, and after the first nested list ends the rest of the list is ignored.

**Code**

https://github.com/mrin9/RapiPdf/blob/6a8055ce5a9ec4d1458d8cae0fb89b0116d1fd7c/src/markdown.js#L84 - this code doesn't seem to ever allow for nested lists.

**Comment by andyrooger** [comment]
It also does not allow multiline bullets, and seems to add bullets to any text following a list from what I can tell

**Comment by mrin9** [comment]
markdown support in PDF is rudimentary, It do not support tables, complex alignments etc too.

However keeping this open now.
a PR will help me a lot here, otherwise I will take a shot at it to support at least the nested list bit later

**Comment by andyrooger** [comment]
#58 Seemed a nice way to tackle list nesting, tables and anything else in one go
