### ISSUE TITLE
Documentation is not rendering

### ISSUE THREAD

**Issue by skeyby** [mrin9/RapiPdf#7]
I was trying to render a documentation from a still-very-early JSON from one of our service, but the PDF is not coming out with an error in Console.

This is the error in SAFARI:

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'i.schema.properties')
	generatorResume (rapipdf-min.js:47:1121664)
	p (rapipdf-min.js:47:1125428)
	i (rapipdf-min.js:47:1131402)
	promiseReactionJob

This is the error in CHROME:

Spec Conversion - Success !!! 
lodash.js:9 Uncaught (in promise) TypeError: Cannot read property 'properties' of undefined
    at h (lodash.js:9)
    at lodash.js:9
    at Array.map (<anonymous>)
    at lodash.js:9
    at A (lodash.js:9)
    at A.next (<anonymous>)
    at p (lodash.js:9)
    at i (lodash.js:9)

This is the error in FIREFOX:

Spec Conversion - Success !!! lodash.js:9
TypeError: i.schema is undefined

The reference is at: https://storage.gcloud.schema31.it/reference/api_1.0.0/openapi.json
Feel free to try it at: https://storage.gcloud.schema31.it/docs/public/api_1.0.0/pdf.php

Thanks, the project looks very cool!

**Comment by mrin9** [comment]
I have made a change to take care of a situation where the schema is missing in the spec. I think thats the case with your spec too.

Can you confirm if it takes care of your situation ?

**Comment by skeyby** [comment]
Yes, it's working now!

I don't exactly get what is be the broken reference (the missing schema) in my spec, but I'll investigate it further...

Thanks.
