### ISSUE TITLE
Support replacement characters ,Non-English language PDF, showing garbled characters

### ISSUE THREAD

**Issue by sain801028** [mrin9/RapiPdf#74]
![螢幕快照_2020-09-25_13-37-33](https://user-images.githubusercontent.com/17377422/94230350-6076c480-ff34-11ea-8831-359c2d6112e6.png)
![螢幕快照_2020-09-25_09-51-26](https://user-images.githubusercontent.com/17377422/94217492-b8053800-ff14-11ea-801d-489c71c04fd3.png)
![螢幕快照_2020-09-25_09-51-17](https://user-images.githubusercontent.com/17377422/94217495-b9366500-ff14-11ea-8e9a-9c6be7654f1a.png)

**Comment by lfc4work** [comment]
@sain801028 How did you solve it? Could you give me a solution?
