### ISSUE TITLE
add convertion from string, not by url

### ISSUE THREAD

**Issue by Glucksistemi** [mrin9/RapiPdf#8]
It would be really great to have an option to generate PDF using copy-paste of text, not by link. For example, I just had to generate API from swagger made by apicur.io and uploaded to my PC. File was protected by NDA so I couldn't upload it to open internet, so I had to install local web-server to open it by your app. So it would be great to have an option to paste json/yaml to textarea in app instead of url requesting

**Comment by mrin9** [comment]
sure, will be provided soon

**Comment by mrin9** [comment]
this is now provided in release 1.1.1.
please use the method `generatePdf()` to create PDFs programmatically and you may provide a valid json spec object .
For usage refer to this [example](https://github.com/mrin9/RapiPdf/blob/master/docs/examples/example1.html)
