### ISSUE TITLE
PDF templates

### ISSUE THREAD

**Issue by Glucksistemi** [mrin9/RapiPdf#9]
It could be great to have a format to upload custom PDF template or something. The case is: names localisation. My API is described in Russian so I would like to have translated headers (like "index", "Request", "request body" etc in generated PDF.

**Comment by mrin9** [comment]
okay, I would bring the localization topic up with the team and look into how best we can address this. Meanwhile can you tell me how do you plan to show the data-types and formats like `string, int, float, double, uuid, array, boolean... etc`
Should they be translated or they would be shown as is ?

**Comment by mrin9** [comment]
localization is now possible (from release `1.1.1`)
Refer to the [API](https://mrin9.github.io/RapiPdf/#api) on how to provide localization
